# Generated by Django 5.2.8 on 2025-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_company_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
