# Generated by Django 5.2.8 on 2025-11-19 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam ou conteúdo promocional'), ('inappropriate', 'Conteúdo inadequado ou ofensivo'), ('false', 'Informação falsa ou enganosa'), ('harassment', 'Assédio ou bullying'), ('other', 'Outro motivo')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descreva o motivo da denúncia (opcional)')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewed', 'Revisado'), ('resolved', 'Resolvido'), ('dismissed', 'Descartado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.review')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('review', 'reporter')},
            },
        ),
    ]
