# Generated by Django 3.2.25 on 2025-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='company_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
