# Generated by Django 3.2.25 on 2025-11-19 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20251115_2040'),
        ('companies', '0002_auto_20251118_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(verbose_name='Descrição do serviço')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='budget_photos/', verbose_name='Fotos')),
                ('desired_date', models.DateField(verbose_name='Data desejada')),
                ('urgency', models.CharField(choices=[('low', 'Baixa (1-2 semanas)'), ('medium', 'Média (3-7 dias)'), ('high', 'Alta (1-2 dias)'), ('emergency', 'Emergência (24 horas)')], default='medium', max_length=20, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('company_response', models.TextField(blank=True, null=True, verbose_name='Resposta do prestador')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço proposto')),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='user.company')),
            ],
            options={
                'verbose_name': 'Solicitação de Orçamento',
                'verbose_name_plural': 'Solicitações de Orçamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
