# Generated by Django 3.2.25 on 2025-11-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_budgetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='client_response',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta do cliente'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='client_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('quoted', 'Orçado'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
